# Railway Nixpacks Configuration - Fixed for Docker BuildKit cache issues

[phases.install]
cmds = [
    "npm cache clean --force",
    "npm install --production --no-package-lock"
]

[start]
cmd = "npm start"
